"""
state.py
--------
Defines the shared state object that flows through the LangGraph agent graph.

In LangGraph, every node reads from and writes to a shared TypedDict state.
Think of this as the "memory" of the multi-agent pipeline — each agent
reads what previous agents produced and adds its own output.

The Annotated[list, operator.add] pattern tells LangGraph to APPEND new items
to these lists rather than replace them — critical for accumulating research
across multiple iterations of the agentic loop.
"""

from typing import Annotated
from typing_extensions import TypedDict
import operator


class ResearchState(TypedDict):
    """
    Shared state passed between all nodes in the research graph.

    Fields:
        topic           : The original research topic from the user.
        search_queries  : List of search queries generated by the Planner.
                          Grows if the Critic requests additional research.
        search_results  : Accumulated raw search results (one entry per query).
        research_notes  : Summarised findings extracted by the Researcher.
                          Grows across iterations of the agentic loop.
        critique        : Feedback from the Critic agent on research completeness.
                          Contains 'RESEARCH_COMPLETE' when done.
        final_report    : The polished Markdown report from the Synthesiser.
        iteration       : Current research iteration count (prevents infinite loops).
        status          : Human-readable pipeline status for UI display.
    """

    topic: str

    # Annotated with operator.add so LangGraph APPENDS to these lists
    # across nodes and loop iterations — not replaces them
    search_queries: Annotated[list[str], operator.add]
    search_results: Annotated[list[str], operator.add]
    research_notes: Annotated[list[str], operator.add]

    critique: str
    final_report: str
    iteration: int
    status: str
